# page 1 Scraping

In [93]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
options = Options()
options.add_argument("--headless=new")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
options.add_argument("accept-language=en-US,en;q=0.9")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                     "AppleWebKit/537.36 (KHTML, like Gecko) "
                     "Chrome/120.0.0.0 Safari/537.36")

driver = webdriver.Chrome(options=options)
driver.get("https://www.amazon.com/s?k=maybelline+mascara&currency=USD")
links = driver.find_elements(By.XPATH, '//div[@class="a-section a-spacing-none a-spacing-top-small s-title-instructions-style"]/a')
product_links = [link.get_attribute("href") + "?currency=USD" for link in links]
print(f"🔗 Total product links found: {len(product_links)}")
titles = []
prices = []
ratings = []
reviews = []
availabilities = []
sellers = []  
for link in product_links:
    try:
        driver.get(link)
        wait = WebDriverWait(driver, 10)
        title = wait.until(EC.presence_of_element_located((By.XPATH, '//span[@id="productTitle"]'))).text
        titles.append(title)
        try:
            price = wait.until(EC.presence_of_element_located(
                (By.XPATH, '//span[contains(@class, "a-offscreen")]')
            )).get_attribute("textContent")
        except:
            price = "N/A"
        prices.append(price)
        try:
            rating = driver.find_element(By.XPATH, '//span[@data-hook="rating-out-of-text"]').text
        except:
            rating = "N/A"
        ratings.append(rating)
        try:
            review = driver.find_element(By.XPATH, '//span[@id="acrCustomerReviewText"]').text
        except:
            review = "N/A"
        reviews.append(review)
        try:
            availability = driver.find_element(By.XPATH, '//div[@id="availability"]//span').text
        except:
            availability = "N/A"
        availabilities.append(availability)
        try:
            seller_text = driver.find_element(By.XPATH, '//a[contains(@href, "offer-listing")]').text
            sellers.append(seller_text)
        except:
            sellers.append("N/A")

    except Exception as e:
        print(f"❌ Error fetching {link[:60]}... → {e}")
        titles.append("N/A")
        prices.append("N/A")
        ratings.append("N/A")
        reviews.append("N/A")
        availabilities.append("N/A")
        sellers.append("N/A")

# --- Step 5: Create DataFrame ---
df = pd.DataFrame({
    "Title": titles,
    "Price (USD)": prices,
    "Rating": ratings,
    "Reviews": reviews,
    "Availability": availabilities,
    "Number of Sellers": sellers,
    "Product Link": product_links
})

driver.quit()

🔗 Total product links found: 48
✅ Maybelline Lash Sensational Sky High Washable Mascara Makeup... | $7.99 | Sellers: New (7) from
$7
99
✅ Maybelline Lash Sensational Sky High Washable Mascara Makeup... | $7.99 | Sellers: New (2) from
$7
99
✅ Maybelline The Colossal Bubble Washable Mascara, Buildable M... | $9.94 | Sellers: N/A
✅ Maybelline Lash Sensational Washable Mascara, Lengthening an... | $8.99 | Sellers: New (4) from
$8
99
✅ Maybelline Lash Sensational Washable Mascara, Lengthening an... | $8.87 | Sellers: New (10) from
$8
55
✅ Maybelline Lash Sensational Washable Mascara, Lengthening an... | $8.99 | Sellers: New (2) from
$8
99
✅ Maybelline Lash Sensational Sky High Washable Mascara, Volum... | $8.98 | Sellers: N/A
✅ Maybelline Great Lash Washable Mascara Makeup, Volumizing La... | $5.99 | Sellers: N/A
✅ Maybelline Great Lash Washable Mascara Makeup, Volumizing La... | $9.98 | Sellers: N/A
✅ Maybelline Volum' Express Colossal Washable Mascara Makeup, ... | $7.53 | Sellers: New (6) from
$7
39
✅ Maybelline Great Lash BIG Washable Mascara, Volumizing, Thic... | $11.98 | Sellers: N/A
✅ Maybelline The Falsies Lash Lift Washable Mascara Volumizing... | $8.99 | Sellers: N/A
✅ Maybelline Great Lash Washable Mascara Makeup, Volumizing La... | $9.99 | Sellers: N/A
✅ Maybelline The Falsies Surreal Extensions Washable Mascara, ... | $8.99 | Sellers: New (3) from
$8
99
✅ Maybelline Great Lash Lots Of Lashes Washable Mascara, Volum... | $11.98 | Sellers: N/A
✅ Maybelline The Falsies Lash Lift Washable Mascara Volumizing... | $8.99 | Sellers: N/A
✅ Maybelline New York Full 'N Soft Washable Mascara, Very Blac... | $6.99 | Sellers: New (2) from
$6
99
✅ Maybelline New York Volum' Express The Colossal Big Shot Was... | $15.27 | Sellers: New (2) from
$15
27
✅ Maybelline Volum' Express The Falsies Washable Fiber Mascara... | $6.96 | Sellers: New (5) from
$6
96
✅ Maybelline The Falsies Surreal Extensions Washable Mascara, ... | $10.98 | Sellers: New (3) from
$9
99
✅ Maybelline Lash Sensational Waterproof Mascara, Lengthening ... | $8.99 | Sellers: New (3) from
$8
97
✅ Maybelline Lash Sensational Firework Washable Mascara, Lengt... | $9.99 | Sellers: New (2) from
$9
99
✅ Maybelline Volum' Express Falsies Push Up Angel Washable Mas... | $7.99 | Sellers: New (4) from
$7
99
✅ Maybelline Lash Stiletto Ultimate Length Washable Mascara, V... | $6.82 | Sellers: N/A
✅ Maybelline Lash Stiletto Ultimate Length Waterproof Mascara,... | $10.98 | Sellers: N/A
✅ Maybelline Volum' Express Colossal Waterproof Mascara Makeup... | $6.99 | Sellers: New (7) from
$6
74
✅ Maybelline New York Total Temptation Washable Mascara, Black... | $9.98 | Sellers: New (6) from
$8
99
✅ Maybelline Volum' Express The Falsies Waterproof Mascara, Vo... | $6.96 | Sellers: New (2) from
$6
96
✅ Maybelline New York Volume Express Colossal Cat Eyes Washabl... | $7.94 | Sellers: New (6) from
$8
25
✅ Maybelline Volum' Express Pumped Up Colossal Mascara, Washab... | $5.99 | Sellers: New (4) from
$5
99
✅ Maybelline The Falsies Surreal Extensions Waterproof Mascara... | $8.99 | Sellers: New (2) from
$8
99
✅ Maybelline Great Lash Mascara, Very Black [101], 0.43 oz (Pa... | After 40 years, Great Lash is still America’s favorite mascara. This mascara features a lash-doubling formula that glides on to build great-looking lashes. The lash-building brush makes it easy to get a full-lash look. Ophthalmologist tested. Hypoallergenic tested. Suitable for contact lens wearers. | Sellers: See All Buying Options
✅ Maybelline Volum' Express Colossal Curl Bounce Washable Curl... | $8.94 | Sellers: New (4) from
$9
40
✅ Maybelline Great Lash Curved Brush Washable Mascara, Volumiz... | $5.82 | Sellers: New (4) from
$5
82
✅ Maybelline New York Volume' Express The Rocket Waterproof Ma... | $8.22 | Sellers: New (3) from
$8
22
✅ Maybelline The Falsies Push Up Drama Washable Mascara, Black... | $25.94 | Sellers: New (4) from
$25
93
✅ Maybelline New York Total Temptation Washable Mascara, Very ... | $9.99 | Sellers: New (3) from
$9
99
✅ Maybelline New York Volum' Express The Colossal Big Shot Wat... | $9.69 | Sellers: New (13) from
$9
69
✅ Maybelline New York Makeup Volum' Express The Falsies Flared... | $6.59 | Sellers: New (4) from
$6
59
✅ Maybelline Volum' Express The Colossal Mascara - Classic Bla... | $9.99 | Sellers: New (3) from
$9
99
✅ Maybelline The Colossal Volum' Express Mascara, Glam Black [... | $7.99 | Sellers: N/A
✅ Maybelline Full 'N Soft Waterproof Mascara, Very Black, 1 Co... | Maybelline New York Full 'N Soft Washable Mascara, Very Black, 1 Count | Sellers: See All Buying Options
✅ Maybelline New York Lash Discovery Mini-Brush Waterproof Mas... |  | Sellers: See All Buying Options
✅ Maybelline New York Volum' Express Pumped Up! Colossal Water... | $7.99 | Sellers: New (5) from
$7
99
✅ Maybelline Lash Sensational Sky High Waterproof Mascara Make... | Maybelline Lash Sensational Sky High Washable Mascara Makeup, Volumizing, Lengthening, Defining, Curling, Multiplying, Buildable Formula, Blackest Black, 1 Count | Sellers: See All Buying Options
✅ Maybelline New York Volum' Express The Colossal Waterproof, ... | $11.85 | Sellers: New (8) from
$10
79
✅ Maybelline Lash Sensational Luscious Washable Mascara, Brown... | $13.99 | Sellers: New (3) from
$13
99
✅ Maybelline Lash Sensational Luscious Mascara, Black, 0.32 Ou... | Maybelline Lash Sensational Washable Mascara, Lengthening and Volumizing for a Full Fan Effect, Blackest Black, 1 Count | Sellers: See All Buying Options

📊 Scraping Completed! Here's your Data:
                                                Title  \
0   Maybelline Lash Sensational Sky High Washable ...
1   Maybelline Lash Sensational Sky High Washable ...
2   Maybelline The Colossal Bubble Washable Mascar...
3   Maybelline Lash Sensational Washable Mascara, ...
4   Maybelline Lash Sensational Washable Mascara, ...
5   Maybelline Lash Sensational Washable Mascara, ...
6   Maybelline Lash Sensational Sky High Washable ...
7   Maybelline Great Lash Washable Mascara Makeup,...
8   Maybelline Great Lash Washable Mascara Makeup,...
9   Maybelline Volum' Express Colossal Washable Ma...
10  Maybelline Great Lash BIG Washable Mascara, Vo...
11  Maybelline The Falsies Lash Lift Washable Masc...
12  Maybelline Great Lash Washable Mascara Makeup,...
13  Maybelline The Falsies Surreal Extensions Wash...
14  Maybelline Great Lash Lots Of Lashes Washable ...
15  Maybelline The Falsies Lash Lift Washable Masc...
16  Maybelline New York Full 'N Soft Washable Masc...
17  Maybelline New York Volum' Express The Colossa...
18  Maybelline Volum' Express The Falsies Washable...
19  Maybelline The Falsies Surreal Extensions Wash...
20  Maybelline Lash Sensational Waterproof Mascara...
21  Maybelline Lash Sensational Firework Washable ...
22  Maybelline Volum' Express Falsies Push Up Ange...
23  Maybelline Lash Stiletto Ultimate Length Washa...
24  Maybelline Lash Stiletto Ultimate Length Water...
25  Maybelline Volum' Express Colossal Waterproof ...
26  Maybelline New York Total Temptation Washable ...
27  Maybelline Volum' Express The Falsies Waterpro...
28  Maybelline New York Volume Express Colossal Ca...
29  Maybelline Volum' Express Pumped Up Colossal M...
30  Maybelline The Falsies Surreal Extensions Wate...
31  Maybelline Great Lash Mascara, Very Black [101...
32  Maybelline Volum' Express Colossal Curl Bounce...
33  Maybelline Great Lash Curved Brush Washable Ma...
34  Maybelline New York Volume' Express The Rocket...
35  Maybelline The Falsies Push Up Drama Washable ...
36  Maybelline New York Total Temptation Washable ...
37  Maybelline New York Volum' Express The Colossa...
38  Maybelline New York Makeup Volum' Express The ...
39  Maybelline Volum' Express The Colossal Mascara...
40  Maybelline The Colossal Volum' Express Mascara...
41  Maybelline Full 'N Soft Waterproof Mascara, Ve...
42  Maybelline New York Lash Discovery Mini-Brush ...
43  Maybelline New York Volum' Express Pumped Up! ...
44  Maybelline Lash Sensational Sky High Waterproo...
45  Maybelline New York Volum' Express The Colossa...
46  Maybelline Lash Sensational Luscious Washable ...
47  Maybelline Lash Sensational Luscious Mascara, ...

                                          Price (USD)        Rating  \
0                                               $7.99  4.5 out of 5
1                                               $7.99  4.5 out of 5
2                                               $9.94    4 out of 5
3                                               $8.99  4.5 out of 5
4                                               $8.87  4.5 out of 5
5                                               $8.99  4.5 out of 5
6                                               $8.98  4.5 out of 5
7                                               $5.99  4.4 out of 5
8                                               $9.98  4.4 out of 5
9                                               $7.53  4.5 out of 5
10                                             $11.98  4.4 out of 5
11                                              $8.99  4.4 out of 5
12                                              $9.99  4.4 out of 5
13                                              $8.99  4.3 out of 5
14                                             $11.98  4.6 out of 5
15                                              $8.99  4.4 out of 5
16                                              $6.99  4.4 out of 5
17                                             $15.27  4.4 out of 5
18                                              $6.96  4.5 out of 5
19                                             $10.98  4.3 out of 5
20                                              $8.99  4.4 out of 5
21                                              $9.99  4.3 out of 5
22                                              $7.99  4.5 out of 5
23                                              $6.82  4.4 out of 5
24                                             $10.98  4.5 out of 5
25                                              $6.99  4.4 out of 5
26                                              $9.98  4.3 out of 5
27                                              $6.96  4.5 out of 5
28                                              $7.94  4.4 out of 5
29                                              $5.99  4.4 out of 5
30                                              $8.99  4.4 out of 5
31  After 40 years, Great Lash is still America’s ...  4.6 out of 5
32                                              $8.94  4.2 out of 5
33                                              $5.82  4.6 out of 5
34                                              $8.22  4.4 out of 5
35                                             $25.94  4.4 out of 5
36                                              $9.99  4.2 out of 5
37                                              $9.69  4.5 out of 5
38                                              $6.59    4 out of 5
39                                              $9.99  4.5 out of 5
40                                              $7.99  4.5 out of 5
41  Maybelline New York Full 'N Soft Washable Masc...  4.4 out of 5
42                                                     4.2 out of 5
43                                              $7.99  4.2 out of 5
44  Maybelline Lash Sensational Sky High Washable ...  4.4 out of 5
45                                             $11.85  4.2 out of 5
46                                             $13.99  4.4 out of 5
47  Maybelline Lash Sensational Washable Mascara, ...  4.4 out of 5

            Reviews                        Availability  \
0   121,048 ratings                            In Stock
1   121,048 ratings                            In Stock
2     4,109 ratings                            In Stock
3   115,144 ratings                            In Stock
4   115,144 ratings                            In Stock
5   115,144 ratings                            In Stock
6   121,048 ratings                            In Stock
7    52,442 ratings                            In Stock
8    52,442 ratings                            In Stock
9    19,716 ratings                            In Stock
10    4,261 ratings                            In Stock
11   25,865 ratings                            In Stock
12   52,442 ratings           Temporarily out of stock.
13    6,113 ratings                            In Stock
14    7,478 ratings                            In Stock
15   25,865 ratings                            In Stock
16    7,605 ratings                            In Stock
17      771 ratings  Only 1 left in stock - order soon.
18   22,250 ratings                            In Stock
19    6,113 ratings                            In Stock
20   20,413 ratings                            In Stock
21    2,418 ratings                            In Stock
22    7,173 ratings                            In Stock
23    6,504 ratings                            In Stock
24    3,105 ratings                            In Stock
25   12,261 ratings                            In Stock
26    2,081 ratings
27    5,043 ratings                            In Stock
28    2,823 ratings                            In Stock
29    4,823 ratings                            In Stock
30    4,393 ratings                            In Stock
31      464 ratings
32    3,639 ratings                            In Stock
33    1,085 ratings                            In Stock
34    1,228 ratings                            In Stock
35    1,612 ratings  Only 9 left in stock - order soon.
36    2,158 ratings                            In Stock
37    2,034 ratings                            In Stock
38      553 ratings  Only 4 left in stock - order soon.
39      312 ratings                            In Stock
40      257 ratings  Only 8 left in stock - order soon.
41    5,845 ratings
42    5,830 ratings
43      640 ratings                            In Stock
44   48,313 ratings
45      652 ratings  Only 6 left in stock - order soon.
46    1,990 ratings                            In Stock
47    2,464 ratings

          Number of Sellers                                       Product Link
0    New (7) from  \n$7\n99  https://www.amazon.com/Maybelline-Volumizing-B...
1    New (2) from  \n$7\n99  https://www.amazon.com/Maybelline-Volumizing-B...
2                       N/A  https://www.amazon.com/Maybelline-Colossal-Was...
3    New (4) from  \n$8\n99  https://www.amazon.com/Maybelline-New-York-Sen...
4   New (10) from  \n$8\n55  https://www.amazon.com/Maybelline-Sensational-...
5    New (2) from  \n$8\n99  https://www.amazon.com/Maybelline-New-York-Sen...
6                       N/A  https://www.amazon.com/Maybelline-Sensational-...
7                       N/A  https://www.amazon.com/Maybelline-New-York-Was...
8                       N/A  https://www.amazon.com/Maybelline-New-York-Was...
9    New (6) from  \n$7\n39  https://www.amazon.com/Maybelline-Express-Colo...
10                      N/A  https://www.amazon.com/Maybelline-New-York-Was...
11                      N/A  https://www.amazon.com/Maybelline-Washable-Vol...
12                      N/A  https://www.amazon.com/Maybelline-New-York-Was...
13   New (3) from  \n$8\n99  https://www.amazon.com/Maybelline-Extensions-W...
14                      N/A  https://www.amazon.com/Maybelline-New-York-Was...
15                      N/A  https://www.amazon.com/Maybelline-Washable-Vol...
16   New (2) from  \n$6\n99  https://www.amazon.com/Maybelline-Makeup-Washa...
17  New (2) from  \n$15\n27  https://www.amazon.com/Maybelline-New-York-Col...
18   New (5) from  \n$6\n96  https://www.amazon.com/Maybelline-Express-Fals...
19   New (3) from  \n$9\n99  https://www.amazon.com/Maybelline-Extensions-W...
20   New (3) from  \n$8\n97  https://www.amazon.com/Maybelline-New-York-Sen...
21   New (2) from  \n$9\n99  https://www.amazon.com/Maybelline-Sensational-...
22   New (4) from  \n$7\n99  https://www.amazon.com/Maybelline-New-York-Was...
23                      N/A  https://www.amazon.com/Maybelline-Stiletto-Ult...
24                      N/A  https://www.amazon.com/Maybelline-New-York-Sti...
25   New (7) from  \n$6\n74  https://www.amazon.com/Maybelline-Express-Colo...
26   New (6) from  \n$8\n99  https://www.amazon.com/Maybelline-Temptation-W...
27   New (2) from  \n$6\n96  https://www.amazon.com/Maybelline-Express-Fals...
28   New (6) from  \n$8\n25  https://www.amazon.com/Maybelline-New-York-Col...
29   New (4) from  \n$5\n99  https://www.amazon.com/Maybelline-York-Washabl...
30   New (2) from  \n$8\n99  https://www.amazon.com/Maybelline-Extensions-W...
31   See All Buying Options  https://www.amazon.com/Maybelline-Great-Lash-M...
32   New (4) from  \n$9\n40  https://www.amazon.com/Maybelline-New-York-Col...
33   New (4) from  \n$5\n82  https://www.amazon.com/Maybelline-New-York-Was...
34   New (3) from  \n$8\n22  https://www.amazon.com/Maybelline-New-York-Exp...
35  New (4) from  \n$25\n93  https://www.amazon.com/Maybelline-New-York-Was...
36   New (3) from  \n$9\n99  https://www.amazon.com/Maybelline-Temptation-W...
37  New (13) from  \n$9\n69  https://www.amazon.com/Maybelline-New-York-Col...
38   New (4) from  \n$6\n59  https://www.amazon.com/Maybelline-Express-Fals...
39   New (3) from  \n$9\n99  https://www.amazon.com/Maybelline-Volum-Expres...
40                      N/A  https://www.amazon.com/Maybelline-Colossal-Vol...
41   See All Buying Options  https://www.amazon.com/Maybelline-Makeup-Water...
42   See All Buying Options  https://www.amazon.com/Maybelline-New-York-Dis...
43   New (5) from  \n$7\n99  https://www.amazon.com/Maybelline-New-York-Col...
44   See All Buying Options  https://www.amazon.com/Maybelline-New-York-Len...
45  New (8) from  \n$10\n79  https://www.amazon.com/Maybelline-New-York-Col...
46  New (3) from  \n$13\n99  https://www.amazon.com/Maybelline-New-York-Sen...
47   See All Buying Options  https://www.amazon.com/Maybelline-Sensational-...

In [114]:
df

,Title,Price (USD),Rating,Reviews,Availability,Number of Sellers,Product Link
0,Maybelline Lash Sensational Sky High Washable ...,$7.99,4.5 out of 5,"121,048 ratings",In Stock,7,https://www.amazon.com/Maybelline-Volumizing-B...
1,Maybelline Lash Sensational Sky High Washable ...,$7.99,4.5 out of 5,"121,048 ratings",In Stock,2,https://www.amazon.com/Maybelline-Volumizing-B...
2,Maybelline The Colossal Bubble Washable Mascar...,$9.94,4 out of 5,"4,109 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Colossal-Was...
3,"Maybelline Lash Sensational Washable Mascara, ...",$8.99,4.5 out of 5,"115,144 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Sen...
4,"Maybelline Lash Sensational Washable Mascara, ...",$8.87,4.5 out of 5,"115,144 ratings",In Stock,10,https://www.amazon.com/Maybelline-Sensational-...
5,"Maybelline Lash Sensational Washable Mascara, ...",$8.99,4.5 out of 5,"115,144 ratings",In Stock,2,https://www.amazon.com/Maybelline-New-York-Sen...
6,Maybelline Lash Sensational Sky High Washable ...,$8.98,4.5 out of 5,"121,048 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
7,"Maybelline Great Lash Washable Mascara Makeup,...",$5.99,4.4 out of 5,"52,442 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
8,"Maybelline Great Lash Washable Mascara Makeup,...",$9.98,4.4 out of 5,"52,442 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
9,Maybelline Volum' Express Colossal Washable Ma...,$7.53,4.5 out of 5,"19,716 ratings",In Stock,6,https://www.amazon.com/Maybelline-Express-Colo...
10,"Maybelline Great Lash BIG Washable Mascara, Vo...",$11.98,4.4 out of 5,"4,261 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
11,Maybelline The Falsies Lash Lift Washable Masc...,$8.99,4.4 out of 5,"25,865 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Washable-Vol...
12,"Maybelline Great Lash Washable Mascara Makeup,...",$9.99,4.4 out of 5,"52,442 ratings",Temporarily out of stock.,N/A,https://www.amazon.com/Maybelline-New-York-Was...
13,Maybelline The Falsies Surreal Extensions Wash...,$8.99,4.3 out of 5,"6,113 ratings",In Stock,3,https://www.amazon.com/Maybelline-Extensions-W...
14,Maybelline Great Lash Lots Of Lashes Washable ...,$11.98,4.6 out of 5,"7,478 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
15,Maybelline The Falsies Lash Lift Washable Masc...,$8.99,4.4 out of 5,"25,865 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Washable-Vol...
16,Maybelline New York Full 'N Soft Washable Masc...,$6.99,4.4 out of 5,"7,605 ratings",In Stock,2,https://www.amazon.com/Maybelline-Makeup-Washa...
17,Maybelline New York Volum' Express The Colossa...,$15.27,4.4 out of 5,771 ratings,Only 1 left in stock - order soon.,2,https://www.amazon.com/Maybelline-New-York-Col...
18,Maybelline Volum' Express The Falsies Washable...,$6.96,4.5 out of 5,"22,250 ratings",In Stock,5,https://www.amazon.com/Maybelline-Express-Fals...
19,Maybelline The Falsies Surreal Extensions Wash...,$10.98,4.3 out of 5,"6,113 ratings",In Stock,3,https://www.amazon.com/Maybelline-Extensions-W...
20,Maybelline Lash Sensational Waterproof Mascara...,$8.99,4.4 out of 5,"20,413 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Sen...
21,Maybelline Lash Sensational Firework Washable ...,$9.99,4.3 out of 5,"2,418 ratings",In Stock,2,https://www.amazon.com/Maybelline-Sensational-...
22,Maybelline Volum' Express Falsies Push Up Ange...,$7.99,4.5 out of 5,"7,173 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Was...
23,Maybelline Lash Stiletto Ultimate Length Washa...,$6.82,4.4 out of 5,"6,504 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Stiletto-Ult...
24,Maybelline Lash Stiletto Ultimate Length Water...,$10.98,4.5 out of 5,"3,105 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Sti...
25,Maybelline Volum' Express Colossal Waterproof ...,$6.99,4.4 out of 5,"12,261 ratings",In Stock,7,https://www.amazon.com/Maybelline-Express-Colo...
26,Maybelline New York Total Temptation Washable ...,$9.98,4.3 out of 5,"2,081 ratings",,6,https://www.amazon.com/Maybelline-Temptation-W...
27,Maybelline Volum' Express The Falsies Waterpro...,$6.96,4.5 out of 5,"5,043 ratings",In Stock,2,https://www.amazon.com/Maybelline-Express-Fals...
28,Maybelline New York Volume Express Colossal Ca...,$7.94,4.4 out of 5,"2,823 ratings",In Stock,6,https://www.amazon.com/Maybelline-New-York-Col...
29,Maybelline Volum' Express Pumped Up Colossal M...,$5.99,4.4 out of 5,"4,823 ratings",In Stock,4,https://www.amazon.com/Maybelline-York-Washabl...
30,Maybelline The Falsies Surreal Extensions Wate...,$8.99,4.4 out of 5,"4,393 ratings",In Stock,2,https://www.amazon.com/Maybelline-Extensions-W...
31,"Maybelline Great Lash Mascara, Very Black [101...","After 40 years, Great Lash is still America’s ...",4.6 out of 5,464 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Great-Lash-M...
32,Maybelline Volum' Express Colossal Curl Bounce...,$8.94,4.2 out of 5,"3,639 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Col...
33,Maybelline Great Lash Curved Brush Washable Ma...,$5.82,4.6 out of 5,"1,085 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Was...
34,Maybelline New York Volume' Express The Rocket...,$8.22,4.4 out of 5,"1,228 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Exp...
35,Maybelline The Falsies Push Up Drama Washable ...,$25.94,4.4 out of 5,"1,612 ratings",Only 9 left in stock - order soon.,4,https://www.amazon.com/Maybelline-New-York-Was...
36,Maybelline New York Total Temptation Washable ...,$9.99,4.2 out of 5,"2,158 ratings",In Stock,3,https://www.amazon.com/Maybelline-Temptation-W...
37,Maybelline New York Volum' Express The Colossa...,$9.69,4.5 out of 5,"2,034 ratings",In Stock,13,https://www.amazon.com/Maybelline-New-York-Col...
38,Maybelline New York Makeup Volum' Express The ...,$6.59,4 out of 5,553 ratings,Only 4 left in stock - order soon.,4,https://www.amazon.com/Maybelline-Express-Fals...
39,Maybelline Volum' Express The Colossal Mascara...,$9.99,4.5 out of 5,312 ratings,In Stock,3,https://www.amazon.com/Maybelline-Volum-Expres...
40,Maybelline The Colossal Volum' Express Mascara...,$7.99,4.5 out of 5,257 ratings,Only 8 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-Colossal-Vol...
41,"Maybelline Full 'N Soft Waterproof Mascara, Ve...",Maybelline New York Full 'N Soft Washable Masc...,4.4 out of 5,"5,845 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Makeup-Water...
42,Maybelline New York Lash Discovery Mini-Brush ...,,4.2 out of 5,"5,830 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Dis...
43,Maybelline New York Volum' Express Pumped Up! ...,$7.99,4.2 out of 5,640 ratings,In Stock,5,https://www.amazon.com/Maybelline-New-York-Col...
44,Maybelline Lash Sensational Sky High Waterproo...,Maybelline Lash Sensational Sky High Washable ...,4.4 out of 5,"48,313 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Len...
45,Maybelline New York Volum' Express The Colossa...,$11.85,4.2 out of 5,652 ratings,Only 6 left in stock - order soon.,8,https://www.amazon.com/Maybelline-New-York-Col...
46,Maybelline Lash Sensational Luscious Washable ...,$13.99,4.4 out of 5,"1,990 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Sen...
47,"Maybelline Lash Sensational Luscious Mascara, ...","Maybelline Lash Sensational Washable Mascara, ...",4.4 out of 5,"2,464 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Sensational-...

In [116]:
df["Number of Sellers"] = df["Number of Sellers"].str.replace("\n", "").str.strip()

In [118]:
import re
df["Number of Sellers"] = df["Number of Sellers"].str.replace(r".*New\s*\((\d+)\)\s*from.*", r"\1", regex=True)

In [120]:
df

,Title,Price (USD),Rating,Reviews,Availability,Number of Sellers,Product Link
0,Maybelline Lash Sensational Sky High Washable ...,$7.99,4.5 out of 5,"121,048 ratings",In Stock,7,https://www.amazon.com/Maybelline-Volumizing-B...
1,Maybelline Lash Sensational Sky High Washable ...,$7.99,4.5 out of 5,"121,048 ratings",In Stock,2,https://www.amazon.com/Maybelline-Volumizing-B...
2,Maybelline The Colossal Bubble Washable Mascar...,$9.94,4 out of 5,"4,109 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Colossal-Was...
3,"Maybelline Lash Sensational Washable Mascara, ...",$8.99,4.5 out of 5,"115,144 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Sen...
4,"Maybelline Lash Sensational Washable Mascara, ...",$8.87,4.5 out of 5,"115,144 ratings",In Stock,10,https://www.amazon.com/Maybelline-Sensational-...
5,"Maybelline Lash Sensational Washable Mascara, ...",$8.99,4.5 out of 5,"115,144 ratings",In Stock,2,https://www.amazon.com/Maybelline-New-York-Sen...
6,Maybelline Lash Sensational Sky High Washable ...,$8.98,4.5 out of 5,"121,048 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
7,"Maybelline Great Lash Washable Mascara Makeup,...",$5.99,4.4 out of 5,"52,442 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
8,"Maybelline Great Lash Washable Mascara Makeup,...",$9.98,4.4 out of 5,"52,442 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
9,Maybelline Volum' Express Colossal Washable Ma...,$7.53,4.5 out of 5,"19,716 ratings",In Stock,6,https://www.amazon.com/Maybelline-Express-Colo...
10,"Maybelline Great Lash BIG Washable Mascara, Vo...",$11.98,4.4 out of 5,"4,261 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
11,Maybelline The Falsies Lash Lift Washable Masc...,$8.99,4.4 out of 5,"25,865 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Washable-Vol...
12,"Maybelline Great Lash Washable Mascara Makeup,...",$9.99,4.4 out of 5,"52,442 ratings",Temporarily out of stock.,N/A,https://www.amazon.com/Maybelline-New-York-Was...
13,Maybelline The Falsies Surreal Extensions Wash...,$8.99,4.3 out of 5,"6,113 ratings",In Stock,3,https://www.amazon.com/Maybelline-Extensions-W...
14,Maybelline Great Lash Lots Of Lashes Washable ...,$11.98,4.6 out of 5,"7,478 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Was...
15,Maybelline The Falsies Lash Lift Washable Masc...,$8.99,4.4 out of 5,"25,865 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Washable-Vol...
16,Maybelline New York Full 'N Soft Washable Masc...,$6.99,4.4 out of 5,"7,605 ratings",In Stock,2,https://www.amazon.com/Maybelline-Makeup-Washa...
17,Maybelline New York Volum' Express The Colossa...,$15.27,4.4 out of 5,771 ratings,Only 1 left in stock - order soon.,2,https://www.amazon.com/Maybelline-New-York-Col...
18,Maybelline Volum' Express The Falsies Washable...,$6.96,4.5 out of 5,"22,250 ratings",In Stock,5,https://www.amazon.com/Maybelline-Express-Fals...
19,Maybelline The Falsies Surreal Extensions Wash...,$10.98,4.3 out of 5,"6,113 ratings",In Stock,3,https://www.amazon.com/Maybelline-Extensions-W...
20,Maybelline Lash Sensational Waterproof Mascara...,$8.99,4.4 out of 5,"20,413 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Sen...
21,Maybelline Lash Sensational Firework Washable ...,$9.99,4.3 out of 5,"2,418 ratings",In Stock,2,https://www.amazon.com/Maybelline-Sensational-...
22,Maybelline Volum' Express Falsies Push Up Ange...,$7.99,4.5 out of 5,"7,173 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Was...
23,Maybelline Lash Stiletto Ultimate Length Washa...,$6.82,4.4 out of 5,"6,504 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Stiletto-Ult...
24,Maybelline Lash Stiletto Ultimate Length Water...,$10.98,4.5 out of 5,"3,105 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-New-York-Sti...
25,Maybelline Volum' Express Colossal Waterproof ...,$6.99,4.4 out of 5,"12,261 ratings",In Stock,7,https://www.amazon.com/Maybelline-Express-Colo...
26,Maybelline New York Total Temptation Washable ...,$9.98,4.3 out of 5,"2,081 ratings",,6,https://www.amazon.com/Maybelline-Temptation-W...
27,Maybelline Volum' Express The Falsies Waterpro...,$6.96,4.5 out of 5,"5,043 ratings",In Stock,2,https://www.amazon.com/Maybelline-Express-Fals...
28,Maybelline New York Volume Express Colossal Ca...,$7.94,4.4 out of 5,"2,823 ratings",In Stock,6,https://www.amazon.com/Maybelline-New-York-Col...
29,Maybelline Volum' Express Pumped Up Colossal M...,$5.99,4.4 out of 5,"4,823 ratings",In Stock,4,https://www.amazon.com/Maybelline-York-Washabl...
30,Maybelline The Falsies Surreal Extensions Wate...,$8.99,4.4 out of 5,"4,393 ratings",In Stock,2,https://www.amazon.com/Maybelline-Extensions-W...
31,"Maybelline Great Lash Mascara, Very Black [101...","After 40 years, Great Lash is still America’s ...",4.6 out of 5,464 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Great-Lash-M...
32,Maybelline Volum' Express Colossal Curl Bounce...,$8.94,4.2 out of 5,"3,639 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Col...
33,Maybelline Great Lash Curved Brush Washable Ma...,$5.82,4.6 out of 5,"1,085 ratings",In Stock,4,https://www.amazon.com/Maybelline-New-York-Was...
34,Maybelline New York Volume' Express The Rocket...,$8.22,4.4 out of 5,"1,228 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Exp...
35,Maybelline The Falsies Push Up Drama Washable ...,$25.94,4.4 out of 5,"1,612 ratings",Only 9 left in stock - order soon.,4,https://www.amazon.com/Maybelline-New-York-Was...
36,Maybelline New York Total Temptation Washable ...,$9.99,4.2 out of 5,"2,158 ratings",In Stock,3,https://www.amazon.com/Maybelline-Temptation-W...
37,Maybelline New York Volum' Express The Colossa...,$9.69,4.5 out of 5,"2,034 ratings",In Stock,13,https://www.amazon.com/Maybelline-New-York-Col...
38,Maybelline New York Makeup Volum' Express The ...,$6.59,4 out of 5,553 ratings,Only 4 left in stock - order soon.,4,https://www.amazon.com/Maybelline-Express-Fals...
39,Maybelline Volum' Express The Colossal Mascara...,$9.99,4.5 out of 5,312 ratings,In Stock,3,https://www.amazon.com/Maybelline-Volum-Expres...
40,Maybelline The Colossal Volum' Express Mascara...,$7.99,4.5 out of 5,257 ratings,Only 8 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-Colossal-Vol...
41,"Maybelline Full 'N Soft Waterproof Mascara, Ve...",Maybelline New York Full 'N Soft Washable Masc...,4.4 out of 5,"5,845 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Makeup-Water...
42,Maybelline New York Lash Discovery Mini-Brush ...,,4.2 out of 5,"5,830 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Dis...
43,Maybelline New York Volum' Express Pumped Up! ...,$7.99,4.2 out of 5,640 ratings,In Stock,5,https://www.amazon.com/Maybelline-New-York-Col...
44,Maybelline Lash Sensational Sky High Waterproo...,Maybelline Lash Sensational Sky High Washable ...,4.4 out of 5,"48,313 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Len...
45,Maybelline New York Volum' Express The Colossa...,$11.85,4.2 out of 5,652 ratings,Only 6 left in stock - order soon.,8,https://www.amazon.com/Maybelline-New-York-Col...
46,Maybelline Lash Sensational Luscious Washable ...,$13.99,4.4 out of 5,"1,990 ratings",In Stock,3,https://www.amazon.com/Maybelline-New-York-Sen...
47,"Maybelline Lash Sensational Luscious Mascara, ...","Maybelline Lash Sensational Washable Mascara, ...",4.4 out of 5,"2,464 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Sensational-...

# scraping multiple pages

In [195]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time

# --- Browser setup ---
options = Options()
options.add_argument("--headless=new")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
options.add_argument("accept-language=en-US,en;q=0.9")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                     "AppleWebKit/537.36 (KHTML, like Gecko) "
                     "Chrome/120.0.0.0 Safari/537.36")

driver = webdriver.Chrome(options=options)

# --- Step 1: Open Amazon homepage and force USD ---
driver.get("https://www.amazon.com/")
driver.add_cookie({"name": "i18n-prefs", "value": "USD"})
driver.add_cookie({"name": "lc-main", "value": "en_US"})
time.sleep(1)

# --- Step 2: Open search page ---
search_url = "https://www.amazon.com/s?k=maybelline+mascara&currency=USD"
driver.get(search_url)

# --- Step 3: Wait and get all pagination links (raw URLs) ---
try:
    WebDriverWait(driver, 10).until(
        EC.presence_of_all_elements_located((By.XPATH, '//a[contains(@aria-label, "Go to page")]'))
    )
    pagination_links = [
        link.get_attribute("href") for link in driver.find_elements(By.XPATH, '//a[contains(@aria-label, "Go to page")]')
    ]
    pagination_links = list(dict.fromkeys(pagination_links))  # remove duplicates
    print(f"📄 Total pagination pages found: {len(pagination_links)}")
except Exception as e:
    print(f"⚠️ Could not find pagination: {e}")
    pagination_links = [search_url]

# --- Step 4: Prepare lists ---
titles, prices, ratings, reviews, availabilities, sellers, product_links_all = [], [], [], [], [], [], []

# --- Step 5: Loop through each pagination link ---
for page_link in pagination_links:
    print(f"\n🌍 Scraping Page: {page_link}")
    driver.get(page_link)

    # Wait for product links
    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.XPATH, '//div[@class="a-section a-spacing-none a-spacing-top-small s-title-instructions-style"]/a'))
        )
    except:
        print("⚠️ No product links found on this page, skipping.")
        continue

    # Collect product links (raw)
    product_links = [
        link.get_attribute("href")
        for link in driver.find_elements(By.XPATH, '//div[@class="a-section a-spacing-none a-spacing-top-small s-title-instructions-style"]/a')
    ]
    print(f"🔗 Products found: {len(product_links)}")

    # --- Inner loop: visit each product ---
    for link in product_links:
        try:
            driver.get(link)
            wait = WebDriverWait(driver, 10)

            # --- Title ---
            title = wait.until(EC.presence_of_element_located((By.XPATH, '//span[@id="productTitle"]'))).text
            titles.append(title)

            # --- Price ---
            try:
                price = wait.until(EC.presence_of_element_located(
                    (By.XPATH, '//span[contains(@class, "a-offscreen")]')
                )).get_attribute("textContent")
                if "PKR" in price:  # Fix if any PKR appears
                    price = price.replace("PKR", "$")
            except:
                price = "N/A"
            prices.append(price)

            # --- Rating ---
            try:
                rating = driver.find_element(By.XPATH, '//span[@data-hook="rating-out-of-text"]').text
            except:
                rating = "N/A"
            ratings.append(rating)

            # --- Reviews ---
            try:
                review = driver.find_element(By.XPATH, '//span[@id="acrCustomerReviewText"]').text
            except:
                review = "N/A"
            reviews.append(review)

            # --- Availability ---
            try:
                availability = driver.find_element(By.XPATH, '//div[@id="availability"]//span').text
            except:
                availability = "N/A"
            availabilities.append(availability)

            # --- Sellers ---
            try:
                seller_text = driver.find_element(By.XPATH, '//a[contains(@href, "offer-listing")]').text
                seller_text = seller_text.replace("\n", "").strip()
                seller_text = seller_text.split("from")[0].strip() if "from" in seller_text else seller_text
            except:
                seller_text = "N/A"
            sellers.append(seller_text)

            product_links_all.append(link)

        except Exception as e:
            print(f"❌ Error fetching {link[:60]} → {e}")
            titles.append("N/A")
            prices.append("N/A")
            ratings.append("N/A")
            reviews.append("N/A")
            availabilities.append("N/A")
            sellers.append("N/A")
            product_links_all.append(link)

# --- Step 6: Create DataFrame ---
df = pd.DataFrame({
    "Title": titles,
    "Price (USD)": prices,
    "Rating": ratings,
    "Reviews": reviews,
    "Availability": availabilities,
    "Number of Sellers": sellers,
    "Product Link": product_links_all
})

# --- Step 7: Display summary ---
pd.set_option('display.max_rows', None)
print("\n📊 Scraping Completed!")
print(f"Total products scraped: {len(df)}")
print(df[["Title", "Price (USD)"]].head())

driver.quit()

📄 Total pagination pages found: 2

🌍 Scraping Page: https://www.amazon.com/s?k=maybelline+mascara&page=2&xpid=JIyzVGwGmOge9&currency=USD&qid=1761154317&ref=sr_pg_2
🔗 Products found: 48

🌍 Scraping Page: https://www.amazon.com/s?k=maybelline+mascara&page=3&xpid=JIyzVGwGmOge9&currency=USD&qid=1761154317&ref=sr_pg_3
🔗 Products found: 48

📊 Scraping Completed!
Total products scraped: 96
                                               Title Price (USD)
0  Maybelline Lash Sensational Luscious Washable ...      $13.99
1  Maybelline New York Lash Stiletto Ultimate Len...      $28.94
2  Maybelline Illegal Length Fiber Extensions Was...      $10.98
3              Maybelline Snapscara Washable Mascara       $9.99
4  COVERGIRL Clump Crusher Mascara, 20X More Volu...       $8.43

In [196]:
df

,Title,Price (USD),Rating,Reviews,Availability,Number of Sellers,Product Link
0,Maybelline Lash Sensational Luscious Washable ...,$13.99,4.4 out of 5,"1,990 ratings",In Stock,New (3),https://www.amazon.com/Maybelline-New-York-Sen...
1,Maybelline New York Lash Stiletto Ultimate Len...,$28.94,4.6 out of 5,831 ratings,Temporarily out of stock.,N/A,https://www.amazon.com/Maybelline-New-York-Sti...
2,Maybelline Illegal Length Fiber Extensions Was...,$10.98,4.3 out of 5,"3,562 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Illegal-Exte...
3,Maybelline Snapscara Washable Mascara,$9.99,3.9 out of 5,"1,663 ratings",In Stock,New (9),https://www.amazon.com/Maybelline-New-York-Sna...
4,"COVERGIRL Clump Crusher Mascara, 20X More Volu...",$8.43,4.4 out of 5,"17,054 ratings",In Stock,New (5),https://www.amazon.com/COVERGIRL-Crusher-LashB...
5,Maybelline Volum' Express The Colossal Washabl...,Maybelline Volum' Express Colossal Washable Ma...,4.5 out of 5,347 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Express-Colo...
6,Maybelline Volum' Express The Falsies Colossal...,$21.91,4.4 out of 5,62 ratings,Only 2 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-Express-Fals...
7,"COVERGIRL Lash Blast Volume Mascara, Long-Wear...",$7.49,4.4 out of 5,"54,344 ratings",In Stock,New (4),https://www.amazon.com/COVERGIRL-Mascara-Long-...
8,Maybelline Green Edition Mega Mousse Mascara M...,$15.46,4.1 out of 5,"1,682 ratings",In Stock,New (7),https://www.amazon.com/Maybelline-New-York-Lig...
9,Maybelline Great Lash Waterproof Mascara - Ver...,$11.98,4.6 out of 5,575 ratings,In Stock,New (3),https://www.amazon.com/Maybelline-Great-Lash-W...
10,Maybelline Volum' Express The Colossal Cat Eye...,Maybelline Volum' Express The Falsies Colossal...,4.4 out of 5,451 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Col...
11,"Maybelline New York, Volum' Express The Rocket...",Maybelline Volum' Express The Rocket Volumizin...,4.4 out of 5,409 ratings,,N/A,https://www.amazon.com/Maybelline-New-York-Exp...
12,Maybelline Volum' Express The Colossal Big Sho...,$12.70,3.8 out of 5,6 ratings,In Stock,New (4),https://www.amazon.com/Maybelline-Express-Colo...
13,Maybelline New York Snapscara Washable Mascara...,$9.99,4.2 out of 5,"7,257 ratings",Only 3 left in stock - order soon.,New (2),https://www.amazon.com/Maybelline-New-York-Sna...
14,Maybelline Volum' Express Pumped Up! Colossal ...,Lashes get amplified! The double collagen form...,4.2 out of 5,29 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Express-Colo...
15,Maybelline New York Define-A-Lash Lengthening ...,$8.99,4.5 out of 5,"1,188 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Define-Lengt...
16,Maybelline New York Makeup Volum' Express The ...,The unique and flexible wand helps to lift and...,4.4 out of 5,761 ratings,,N/A,https://www.amazon.com/Maybelline-Express-Fals...
17,"Maybelline New York Lash Sensational Mascara, ...",$8.98,4.1 out of 5,78 ratings,In Stock,New (2),https://www.amazon.com/Maybelline-New-York-Sen...
18,Maybelline New York Volume Express Mega Plush ...,Maybelline Volum' Express Pumped Up Colossal M...,4.4 out of 5,"1,754 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Was...
19,Maybelline New York Lash Discovery Washable Ma...,Maybelline New York Lash Discovery Washable Ma...,4.6 out of 5,413 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Dis...
20,Maybelline New York Volum' Express The Colossa...,$18.42,4.6 out of 5,950 ratings,,N/A,https://www.amazon.com/Maybelline-Volum-Expres...
21,Maybelline New York Volum' Express The Rocket ...,Maybelline Volum' Express The Rocket Volumizin...,4.3 out of 5,168 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Bro...
22,L'Oreal Paris Makeup Telescopic Original Lengt...,$10.77,4.5 out of 5,"75,814 ratings",In Stock,New (5),https://www.amazon.com/Paris-Telescopic-Origin...
23,Maybelline New York Volum' Express The Mega Pl...,Maybelline New York Volume Express Mega Plush ...,4.7 out of 5,26 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Exp...
24,Maybelline New York Lash Sensational Sky High ...,Maybelline Lash Sensational Sky High Washable ...,4.6 out of 5,465 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Sen...
25,"Maybelline Full 'N Soft Waterproof Mascara, Ve...",Maybelline New York Full 'N Soft Washable Masc...,4.6 out of 5,512 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Full-Waterpr...
26,Maybelline New York Great Lash Waterproof Masc...,"Maybelline Great Lash BIG Washable Mascara, Vo...",4.7 out of 5,10 ratings,,N/A,https://www.amazon.com/Maybelline-New-York-Mas...
27,Maybelline Great Lash Lots of Lashes Washable ...,Maybelline Great Lash Lots Of Lashes Washable ...,4.1 out of 5,19 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Lashes-Washa...
28,Maybelline Lash Sensational Sky High Washable ...,"Bemkoo Collapsible Laundry Basket, 90L Large F...",4.6 out of 5,497 ratings,,N/A,https://www.amazon.com/Maybelline-Mascara-Tint...
29,Maybelline New York Volum' Express The Falsies...,The unique and flexible wand helps to lift and...,4.6 out of 5,12 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Express-Fals...
30,Maybelline Great Lash Mascara - Blackest Black...,"After 40 years, Great Lash is still America’s ...",4.3 out of 5,18 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-Great-Lash-M...
31,L'Oreal Paris Makeup Double Extend Tubing Masc...,$11.57,4.4 out of 5,"18,291 ratings",In Stock,New (4),https://www.amazon.com/LOr%C3%A9al-Paris-Makeu...
32,Maybelline New York Lots of Lashes Washable Ma...,Myb Masc Grt Lsh Lots Vry Size .43 O Maybellin...,3.9 out of 5,4 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Was...
33,MAYBELLINE NEW YORK Great Lash Big Washable Ma...,"Maybelline Great Lash BIG Washable Mascara, Vo...",4.1 out of 5,22 ratings,,See All Buying Options,https://www.amazon.com/MAYBELLINE-Great-Washab...
34,Maybelline New York Volum' express the colossa...,$8.49,4.2 out of 5,196 ratings,Only 1 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-New-York-col...
35,Maybelline New York Volum' Express The Falsies...,Maybelline Volum' Express The Falsies Waterpro...,4.2 out of 5,61 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Wat...
36,Maybelline Colossal Volume Express,Maybelline Volum' Express Colossal Washable Ma...,4.3 out of 5,128 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Col...
37,Maybelline New York Volum' Express The Colossa...,$13.95,4 out of 5,759 ratings,Only 8 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-New-York-Exp...
38,Maybelline The Colossal Volum' Express Waterpr...,Maybelline Volum' Express The Colossal Mascara...,4.2 out of 5,"21,942 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-Colossal-Exp...
39,"CoverGirl Lash Blast Clean Volume Mascara, Veg...",$9.86,4.4 out of 5,"18,115 ratings",In Stock,New (3),https://www.amazon.com/CoverGirl-Mascara-Formu...
40,Maybelline New York The Falsies Push Up Angel ...,Maybelline Volum' Express Falsies Push Up Ange...,4.2 out of 5,"1,075 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Fal...
41,Maybelline New York Volume' Express Falsies Fl...,$8.90,4.2 out of 5,8 ratings,Only 1 left in stock - order soon.,New (2),https://www.amazon.com/Maybelline-New-York-Was...
42,Maybelline The Colossal Volum' Express Mascara...,$32.38,5 out of 5,5 ratings,Only 8 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-Colossal-Exp...
43,Maybelline Volum' Express The Falsies Colossal...,$35.42,5 out of 5,8 ratings,Only 8 left in stock - order soon.,New (2),https://www.amazon.com/Maybelline-Express-Fals...
44,Maybelline Lash Sensational Sky High Mascara 7...,$14.26,4.2 out of 5,379 ratings,,New (3),https://www.amazon.com/Maybelline-Lash-Sensati...
45,Myb Masc Grt Lsh Lots Vry Size .43 O Maybellin...,$12.78,4.8 out of 5,8 ratings,Only 2 left in stock - order soon.,N/A,https://www.amazon.com/Maybelline-Great-Mascar...
46,L’Oreal Paris Makeup Voluminous Original Volum...,$9.97,4.4 out of 5,"95,585 ratings",In Stock,New (4),https://www.amazon.com/LOreal-Paris-Voluminous...
47,Myb Masc Grt L/C Vry Blck Size 365mc,$11.98,N/A,N/A,Only 10 left in stock - order soon.,N/A,https://www.amazon.com/Myb-Masc-Blck-Size-365m...
48,"Maybelline Great Lash BIG Washable Mascara, Vo...",$11.98,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Washable-Vol...
49,MAYBELLINE NEW YORK Great Lash Big Washable Ma...,"Maybelline Great Lash BIG Washable Mascara, Vo...",4.1 out of 5,22 ratings,,See All Buying Options,https://www.amazon.com/MAYBELLINE-Great-Washab...
50,Maybelline Lash Sensational Sky High & Lash Se...,$18.94,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
51,Maybelline New York Volum' Express The Falsies...,$8.99,4.2 out of 5,61 ratings,,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Wat...
52,Maybelline New York Volume' Express Falsies Fl...,$8.90,4.2 out of 5,8 ratings,Only 1 left in stock - order soon.,New (2),https://www.amazon.com/Maybelline-New-York-Was...
53,Maybelline New York Volum' Express The Falsies...,$21.16,4.4 out of 5,"1,003 ratings",In Stock,N/A,https://www.amazon.com/Maybelline-Express-Fals...
54,Maybelline Lash Sensational Sky High Waterproo...,$9.99,5 out of 5,1 rating,,N/A,https://www.amazon.com/Maybelline-Sensational-...
55,Maybelline Lash Sensational Sky High Mascara 2...,$17.98,5 out of 5,1 rating,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
56,Maybelline Lash Sensational Sky High Mascara 7...,$14.26,4.2 out of 5,379 ratings,,New (3),https://www.amazon.com/Maybelline-Lash-Sensati...
57,Maybelline Lash Sensational Sky High Washable ...,$7.99,5 out of 5,1 rating,,N/A,https://www.amazon.com/Maybelline-Sensational-...
58,Maybelline New York The Falsies Push Up Angel ...,"Achieve The Falsies push-up effect, now with a...",4.2 out of 5,"1,075 ratings",,See All Buying Options,https://www.amazon.com/Maybelline-New-York-Fal...
59,Maybelline Lash Sensational Sky High Mascara 2...,HHQQWZ Makeup Bag Travel Cosmetic Bag for Wome...,1 out of 5,1 rating,,N/A,https://www.amazon.com/Maybelline-Sensational-...
60,Maybelline Lash Sensational Waterproof Mascara...,"Maybelline New York Lash Sensational Mascara, ...",5 out of 5,3 ratings,,N/A,https://www.amazon.com/Maybelline-Sensational-...
61,"Maybelline Lash Sensational Washable Mascara, ...",$16.94,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
62,"Maybelline Brow Fast Sculpt, Shapes Eyebrows, ...",,4.3 out of 5,"7,961 ratings",,N/A,https://www.amazon.com/Maybelline-New-York-Eye...
63,"Maybelline Lash Sensational Sky High Mascaras,...",$15.82,3 out of 5,6 ratings,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
64,Myb Masc Grt L/C Vry Blck Size 365mc,$11.98,N/A,N/A,Only 10 left in stock - order soon.,N/A,https://www.amazon.com/Myb-Masc-Blck-Size-365m...
65,Maybelline Lash Sensational Sky High Washable ...,$19.66,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
66,Maybelline Lash Sensational Sky High & Lash Se...,$7.99,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Sensational-...
67,L’Oreal Paris Makeup Voluminous Original Volum...,$9.97,4.4 out of 5,"95,585 ratings",In Stock,New (4),https://www.amazon.com/LOreal-Paris-Voluminous...
68,Maybelline Lash Sensational Sky High Waterproo...,$9.99,4.7 out of 5,3 ratings,,N/A,https://www.amazon.com/Maybelline-Sensational-...
69,Maybelline Lash Sensational Sky High Mascara 2...,$7.99,5 out of 5,5 ratings,,N/A,https://www.amazon.com/Maybelline-Sensational-...
70,"Maybelline Lash Sensational Washable Mascara, ...",$18.62,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
71,"Maybelline Lash Sensational Washable Mascara, ...",$16.94,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
72,Maybelline Lash Sensational Holiday Makeup Kit...,$20.00,4.8 out of 5,17 ratings,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
73,Maybelline Lash Sensational Sky High Washable ...,$15.98,5 out of 5,1 rating,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
74,Maybelline Lash Sensational Sky High Washable ...,$17.66,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
75,COVERGIRL Professional Remarkable Waterproof M...,$5.97,4.3 out of 5,"2,260 ratings",In Stock,New (3),https://www.amazon.com/COVERGIRL-Professional-...
76,Maybelline Lash Sensational Sky High Mascara B...,$7.99,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Sensational-...
77,L'Oreal Paris Cosmetics Voluminous Superstar M...,$10.01,4.5 out of 5,"3,705 ratings",In Stock,New (2),https://www.amazon.com/Paris-Cosmetics-Volumin...
78,"Maybelline Lash Sensational Washable Mascara, ...",$15.91,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Sensational-...
79,"L'Oreal Paris Paradise Big Deal Mascara, Volum...",$12.17,4.3 out of 5,"2,754 ratings",In Stock,N/A,https://www.amazon.com/LOreal-Paris-Volumizing...
80,L'Oreal Paris Voluminous Lash Boosting Conditi...,$9.97,4.5 out of 5,"46,943 ratings",In Stock,New (6),https://www.amazon.com/Paris-Voluminous-Boosti...
81,Maybelline The Falsies Lash Lift Waterproof Ma...,,4.2 out of 5,19 ratings,,N/A,https://www.amazon.com/Maybelline-Falsies-Wate...
82,MAYBELLINE New York Eyestudio Master Precise A...,$17.90,5 out of 5,2 ratings,In Stock,N/A,https://www.amazon.com/MAYBELLINE-Waterproof-S...
83,Maybelline Lash Sensational Mascara 1 Count an...,$12.83,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
84,Neutrogena Healthy Lengths Mascara - with Vita...,$7.62,4.2 out of 5,"7,817 ratings",In Stock,New (3),https://www.amazon.com/Neutrogena-Clump-Free-F...
85,"Revlon ColorStay Full Time Mascara, Volumizing...",$9.97,4.1 out of 5,400 ratings,In Stock,N/A,https://www.amazon.com/ColorStay-Volumizing-Cl...
86,Maybelline Lash Sensational Sky High Washable ...,$8.99,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Sensational-...
87,"e.l.f. Lash 'N Roll Mascara, Curling Mascara F...",$7.00,4.4 out of 5,"8,692 ratings",In Stock,New (2),https://www.amazon.com/l-f-Mascara-Separates-L...
88,"Covergirl Lash Blast Fusion Mascara, Black",$8.99,4.4 out of 5,"6,564 ratings",In Stock,New (3),https://www.amazon.com/COVERGIRL-LashBlast-Fus...
89,Maybelline Lash Sensational Mascara and Instan...,$18.62,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
90,Maybelline Lash Sensational Mascara and Fit Me...,$8.99,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Sensational-...
91,Maybelline Lash Sensational Sky High Glitter M...,$16.07,5 out of 5,2 ratings,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
92,Maybelline Lash Sensational Holiday Makeup Kit...,$30.00,4.6 out of 5,13 ratings,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
93,Maybelline Lash Sensational Sky High Mascara a...,$17.98,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
94,Maybelline Lash Sensational Sky High Mascara a...,$17.98,N/A,N/A,In Stock,N/A,https://www.amazon.com/Maybelline-Sensational-...
95,Maybelline Mascara and Eyebrow Definer Pencil ...,$9.99,N/A,N/A,,N/A,https://www.amazon.com/Maybelline-Mascara-Eyeb...

In [201]:
pd.to_csv("C:\Users\ABC\OneDrive - Notley Green Primary School\Documents\data Analytics completed projects\Projects\Amazon Web Scraping\Amazon Products (Maybelline).csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (149437476.py, line 1)